render_rgb_camera: true

termination_on_run: true
stopped_termination_seconds: 90

reward_failure: -10.0
reward_success: 10.0
reward_wrong_lane: -1.0
reward_steer: -0.1
reward_speed: 0.1
reward_max_speed: 30.0

ip: localhost
port: 2000
tm_port: 8000
seed: 0
timeout: 30.0
fixed_delta_seconds: 0.1
max_substeps: 15

# if false: cycle throw all the scenarios
pick_random: false

run_type: route
route: srunner/data/routes_training.xml
scenario_file: srunner/data/all_towns_traffic_scenarios.json
single_route: null
criteria_enable: true

# scenario
# run_type: scenario
# scenario: None
# randomize: True

# free ride
# run_type: free ride # can be w/e except route and scenario
# num_of_vehicles: 10
# map: null
# num_of_walkers: 10
